-- Unified Service Scheduler — schema (structure only).
-- Portable DDL: SQL-standard IDENTITY columns supported by both H2 and PostgreSQL.

CREATE TABLE customer (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(64)
);

CREATE TABLE dealership (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,
    -- Storefront attributes (address, geo for distance, rating, "usual" flag).
    address      VARCHAR(255) NOT NULL,
    rating       DOUBLE PRECISION NOT NULL,
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    usual        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE vehicle (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer (id),
    vin         VARCHAR(64) NOT NULL UNIQUE,
    make        VARCHAR(128) NOT NULL,
    model       VARCHAR(128) NOT NULL,
    model_year  INT NOT NULL
);
CREATE INDEX idx_vehicle_customer ON vehicle (customer_id);

CREATE TABLE service_type (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(64) NOT NULL UNIQUE,
    name             VARCHAR(255) NOT NULL,
    duration_minutes INT NOT NULL,
    required_skill   VARCHAR(128) NOT NULL,
    price            INT NOT NULL,
    description      VARCHAR(255) NOT NULL
);

CREATE TABLE service_bay (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealership_id BIGINT NOT NULL REFERENCES dealership (id),
    name          VARCHAR(128) NOT NULL
);
CREATE INDEX idx_bay_dealership ON service_bay (dealership_id);

CREATE TABLE technician (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealership_id BIGINT NOT NULL REFERENCES dealership (id),
    name          VARCHAR(255) NOT NULL
);
CREATE INDEX idx_technician_dealership ON technician (dealership_id);

CREATE TABLE technician_skill (
    technician_id BIGINT NOT NULL REFERENCES technician (id),
    skill         VARCHAR(128) NOT NULL,
    PRIMARY KEY (technician_id, skill)
);

CREATE TABLE appointment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dealership_id   BIGINT NOT NULL REFERENCES dealership (id),
    customer_id     BIGINT NOT NULL REFERENCES customer (id),
    vehicle_id      BIGINT NOT NULL REFERENCES vehicle (id),
    technician_id   BIGINT NOT NULL REFERENCES technician (id),
    service_bay_id  BIGINT NOT NULL REFERENCES service_bay (id),
    service_type_id BIGINT NOT NULL REFERENCES service_type (id),
    start_time      TIMESTAMP NOT NULL,
    end_time        TIMESTAMP NOT NULL,
    status          VARCHAR(32) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Indexes backing the overlap ("not exists") availability queries.
CREATE INDEX idx_appt_technician_window ON appointment (technician_id, start_time, end_time);
CREATE INDEX idx_appt_bay_window ON appointment (service_bay_id, start_time, end_time);
CREATE INDEX idx_appt_dealership ON appointment (dealership_id);
